FROM python:3.13-slim

WORKDIR /home/jkspiv/projects/RecipeShop

COPY reqirements.txt .

RUN pip install --no-cache-dir -r reqirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
