services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token "${CLOUDFLARE_TUNNEL_TOKEN}"
    depends_on:
      - backend
      - frontend
    networks:
      - tunnel-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    env_file:
      - .env.production
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - backend-network
      - tunnel-network

  frontend:
    build:
      context: ./App/next-app
      dockerfile: Dockerfile
    container_name: frontend
    env_file: .env.production
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - backend-network
      - frontend-network
      - tunnel-network

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge
  tunnel-network:
